### ISSUE TITLE
Missing data/titles.xlsx

### ISSUE THREAD

**Issue by agstn** [atorus-research/CDISC_pilot_replication#1]
Impressive work on replicating the CDISC Pilot project with R and releasing both the reproducible R code and pharmaRTF package for table generation as open source. I was able to obtain the data for your work using the setup instructions. I was not able to get the **titles.xlxs** to create titles and footnotes. Is that file something you can share?

```
doc <- rtf_doc(final, header_rows = 2) %>% 
   titles_and_footnotes_from_df(
     from.file='./data/titles.xlsx', 
     reader=example_custom_reader,
     table_number='14-6.01') %>%
  set_font_size(10) %>%
  set_ignore_cell_padding(TRUE) %>%
  set_column_header_buffer(top=1)
```

Thanks,

**Comment by atorus-research** [comment]
Thanks for catching this! The file has been added to the repository.
