### ISSUE TITLE
summarize() or dplyr::summarize()?

### ISSUE THREAD

**Issue by xiaohuagong** [atorus-research/CDISC_pilot_replication#4]
In R console, when the runtime environment is not in a clean state, thefunction call of `summarize()` may fail due to the identical function names existing in both packages of `dplyr` and `plyr`.  

One easy fix is to prefix with `dplyr::` or `plyr::` whichever is intended.  

RStudio Server Pro (v1.3+) offers a convenient new feature, [Global Replace](https://blog.rstudio.com/2020/03/17/rstudio-1-3-the-little-things/), for search and replace a string or a regex in all files in a project or inside a folder, etc.

**Comment by atorus-research** [comment]
Thank you for this feedback! We've made the necessary updates to address this. 
- `plyr` as an import has been removed completely
- In cases where `plyr` functions are being used, `plyr::` was added to explicitly state that it was a `plyr` function and avoid any conflicts within the namespace.
